# Generated by Django 4.0.4 on 2022-09-09 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0005_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studys',
            name='pictures',
        ),
        migrations.AddField(
            model_name='studys',
            name='credit',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='studys',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.date(2022, 9, 9)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.date(2022, 9, 15)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.date(2022, 10, 8)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.date(2022, 11, 7)),
        ),
    ]
