# Generated by Django 4.1 on 2022-09-09 16:48

import datetime
from django.db import migrations, models
import study_plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0006_remove_studys_pictures_studys_credit_studys_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studys',
            name='pdf',
            field=models.FileField(blank=True, default=None, upload_to=study_plan.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.date(2022, 9, 10)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.date(2022, 9, 16)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.date(2022, 10, 9)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.date(2022, 11, 8)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='teaching_audio',
            field=models.FileField(default=None, upload_to=study_plan.models.get_upload_path),
        ),
    ]
