# Generated by Django 4.1 on 2022-09-09 16:53

from django.db import migrations, models
import study_plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0009_alter_studys_pdf_alter_studys_teaching_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studys',
            name='teaching_audio',
            field=models.FileField(default='', upload_to=study_plan.models.get_upload_path),
        ),
    ]
