# Generated by Django 4.1 on 2022-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0010_alter_studys_teaching_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studys',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
