# Generated by Django 4.1 on 2022-09-09 20:08

from django.db import migrations, models
import study_plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0011_alter_studys_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studys',
            name='pdf',
            field=models.FileField(blank=True, default='', max_length=1000, upload_to=study_plan.models.get_upload_path),
        ),
    ]
