# Generated by Django 4.0.4 on 2022-09-10 19:42

import datetime
from django.db import migrations, models
import study_plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0012_alter_studys_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='studys',
            name='area',
            field=models.ManyToManyField(blank=True, related_name='studys_area', to='study_plan.subarea'),
        ),
        migrations.RemoveField(
            model_name='studys',
            name='pdf',
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.date(2022, 9, 11)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.date(2022, 9, 17)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.date(2022, 10, 10)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.date(2022, 11, 9)),
        ),
        migrations.RemoveField(
            model_name='studys',
            name='teaching_audio',
        ),
        migrations.AlterField(
            model_name='studys',
            name='topic',
            field=models.ManyToManyField(blank=True, related_name='studys_topic', to='study_plan.subtopic'),
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='doc_file', max_length=200)),
                ('type', models.CharField(choices=[('pdf', 'pdf'), ('mp3', 'mp3')], default='pdf', max_length=10)),
                ('file', models.FileField(default='', upload_to=study_plan.models.get_upload_path)),
                ('area', models.ManyToManyField(blank=True, related_name='files_by_area', to='study_plan.subarea')),
                ('topic', models.ManyToManyField(blank=True, related_name='files_by_topic', to='study_plan.subtopic')),
            ],
        ),
        migrations.AddField(
            model_name='studys',
            name='pdf',
            field=models.ManyToManyField(blank=True, default='', max_length=1000, related_name='pdf_docs', to='study_plan.docs'),
        ),
        migrations.AddField(
            model_name='studys',
            name='teaching_audio',
            field=models.ManyToManyField(blank=True, default='', max_length=1000, related_name='audio_docs', to='study_plan.docs'),
        ),
    ]
