# Generated by Django 4.0.4 on 2022-09-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0013_studys_area_remove_studys_pdf_alter_studys_rev1_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='name',
        ),
    ]
