# Generated by Django 4.0.4 on 2022-09-12 02:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import study_plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0014_remove_docs_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.FileField(upload_to=study_plan.models.get_upload_path_certifications)),
                ('nivel', models.CharField(choices=[('basic', 'basic'), ('Intermediary', 'Intermediary'), ('Advanced', 'Advanced')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.FileField(default='', upload_to=study_plan.models.get_upload_path_courses)),
                ('course_model', models.CharField(choices=[('face-to-face', 'face-to-face'), ('distance', 'distance')], default='distance', max_length=50)),
                ('duration', models.CharField(choices=[('1 months - 2 months', '1 months - 2 months'), ('2 months - 4 months', '2 months - 4 months'), ('4 months - 8 months', '4 months - 8 months')], default='1 months - 2 months', max_length=50)),
                ('areas', models.ManyToManyField(related_name='courses_area', to='study_plan.subarea')),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_plan.certificates')),
            ],
        ),
        migrations.CreateModel(
            name='HardSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.FileField(upload_to=study_plan.models.get_upload_path_hardskills)),
            ],
        ),
        migrations.CreateModel(
            name='SoftSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.FileField(upload_to=study_plan.models.get_upload_path_softkills)),
            ],
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.date(2022, 9, 12)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.date(2022, 9, 18)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.date(2022, 10, 11)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.date(2022, 11, 10)),
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('videos', models.CharField(max_length=500)),
                ('audio', models.FileField(upload_to=study_plan.models.get_upload_path_lessons)),
                ('notes', models.TextField(max_length=50000)),
                ('slides', models.FileField(upload_to=study_plan.models.get_upload_path_lessons)),
                ('source_code', models.FileField(upload_to=study_plan.models.get_upload_path_lessons)),
                ('subtitles', models.FileField(upload_to=study_plan.models.get_upload_path_lessons)),
                ('transcript', models.TextField(max_length=50000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons_course', to='study_plan.courses')),
                ('hard_skills', models.ManyToManyField(related_name='lessons_hard_skills', to='study_plan.hardskills')),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(upload_to=study_plan.models.get_upload_path_institutions)),
                ('courses', models.ManyToManyField(related_name='institution_courses', to='study_plan.courses')),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='credits',
            field=models.ManyToManyField(related_name='courses_institutions', to='study_plan.institutions'),
        ),
        migrations.AddField(
            model_name='courses',
            name='hard_skills',
            field=models.ManyToManyField(related_name='courses_hard_skills', to='study_plan.hardskills'),
        ),
        migrations.AddField(
            model_name='courses',
            name='instructors',
            field=models.ManyToManyField(related_name='courses_instructors', to='study_plan.instructors'),
        ),
        migrations.AddField(
            model_name='courses',
            name='lessons',
            field=models.ManyToManyField(related_name='course_lessons', to='study_plan.lessons'),
        ),
        migrations.AddField(
            model_name='courses',
            name='topics',
            field=models.ManyToManyField(related_name='courses_topic', to='study_plan.subtopic'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='course',
            field=models.ManyToManyField(related_name='certificate_course', to='study_plan.courses'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='institutions',
            field=models.ManyToManyField(related_name='certificate_institution', to='study_plan.institutions'),
        ),
    ]
