# Generated by Django 4.0.4 on 2022-09-12 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0015_certificates_courses_hardskills_softskills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 13, 2, 14, 33, 416911, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 2, 14, 33, 416911, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 2, 14, 33, 416911, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 11, 2, 14, 33, 416911, tzinfo=utc)),
        ),
    ]
