# Generated by Django 4.1 on 2022-09-13 20:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0017_remove_instructors_name_instructors_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='certificate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='study_plan.certificates'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='hard_skills',
            field=models.ManyToManyField(blank=True, related_name='courses_hard_skills', to='study_plan.hardskills'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='lessons',
            field=models.ManyToManyField(blank=True, related_name='course_lessons', to='study_plan.lessons'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='course_rooms', to='study_plan.rooms'),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='institution_courses', to='study_plan.courses'),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 14, 20, 6, 4, 594941, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 20, 20, 6, 4, 594941, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 13, 20, 6, 4, 594941, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 12, 20, 6, 4, 594941, tzinfo=datetime.timezone.utc)),
        ),
    ]
