# Generated by Django 4.1 on 2022-09-13 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0021_alter_studys_rev1_date_alter_studys_rev2_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='credits',
            field=models.ManyToManyField(blank=True, related_name='courses_institutions', to='study_plan.institutions'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses_instructors', to='study_plan.instructors'),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 14, 20, 19, 42, 523562, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 20, 20, 19, 42, 523562, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 13, 20, 19, 42, 523562, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 12, 20, 19, 42, 523562, tzinfo=datetime.timezone.utc)),
        ),
    ]
