# Generated by Django 4.1 on 2022-09-14 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0025_alter_lessons_notes_alter_lessons_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='hard_skills',
            field=models.ManyToManyField(blank=True, related_name='lessons_hard_skills', to='study_plan.hardskills'),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='transcript',
            field=models.TextField(max_length=150000),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 15, 13, 8, 28, 790666, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 21, 13, 8, 28, 790666, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 14, 13, 8, 28, 790666, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 13, 8, 28, 790666, tzinfo=datetime.timezone.utc)),
        ),
    ]
