# Generated by Django 4.1 on 2022-09-14 13:10

import datetime
from django.db import migrations, models
import study_plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0026_alter_lessons_hard_skills_alter_lessons_transcript_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='audio',
            field=models.FileField(max_length=500, upload_to=study_plan.models.get_upload_path_lessons),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='slides',
            field=models.FileField(max_length=500, upload_to=study_plan.models.get_upload_path_lessons),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='source_code',
            field=models.FileField(max_length=500, upload_to=study_plan.models.get_upload_path_lessons),
        ),
        migrations.AlterField(
            model_name='lessons',
            name='subtitles',
            field=models.FileField(max_length=500, upload_to=study_plan.models.get_upload_path_lessons),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 15, 13, 10, 24, 691032, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 21, 13, 10, 24, 691032, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 14, 13, 10, 24, 691032, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 13, 10, 24, 691032, tzinfo=datetime.timezone.utc)),
        ),
    ]
