# Generated by Django 4.1 on 2022-09-14 13:41

import datetime
from django.db import migrations, models
import study_plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0028_alter_studys_rev1_date_alter_studys_rev2_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='source_code',
            field=models.FileField(blank=True, max_length=500, upload_to=study_plan.models.get_upload_path_lessons),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 15, 13, 41, 2, 402062, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 21, 13, 41, 2, 403059, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 14, 13, 41, 2, 403059, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 13, 41, 2, 403059, tzinfo=datetime.timezone.utc)),
        ),
    ]
