# Generated by Django 4.1 on 2022-09-14 14:13

import datetime
from django.db import migrations, models
import django.db.models.deletion
import study_plan.models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0029_alter_lessons_source_code_alter_studys_rev1_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 15, 14, 13, 32, 457899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 21, 14, 13, 32, 457899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 14, 14, 13, 32, 457899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 14, 13, 32, 457899, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_image', models.FileField(max_length=500, upload_to=study_plan.models.get_upload_path_projects)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_project', to='study_plan.lessons')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='lesson_project', to='study_plan.projects'),
        ),
    ]
