# Generated by Django 4.1 on 2022-09-14 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0041_alter_lessons_notes_alter_studys_rev1_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='getting_started',
            field=models.TextField(blank=True, default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='hints',
            field=models.TextField(blank=True, default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='how_to_send',
            field=models.TextField(blank=True, default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='projects',
            name='specifications',
            field=models.TextField(blank=True, default='', max_length=100000),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 15, 15, 13, 5, 289127)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 21, 15, 13, 5, 289127)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 14, 15, 13, 5, 289127)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 15, 13, 5, 289127)),
        ),
    ]
