# Generated by Django 4.1 on 2022-09-14 18:35

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0042_alter_projects_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='rooms_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 15, 15, 35, 12, 168388)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 21, 15, 35, 12, 168388)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 14, 15, 35, 12, 168388)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 13, 15, 35, 12, 168388)),
        ),
    ]
