# Generated by Django 4.0.4 on 2022-09-15 01:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('study_plan', '0044_alter_studys_rev1_date_alter_studys_rev2_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessons',
            old_name='videos',
            new_name='video',
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev1_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 16, 1, 35, 54, 739677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev2_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 22, 1, 35, 54, 739677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev3_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 15, 1, 35, 54, 739677, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='studys',
            name='rev4_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 14, 1, 35, 54, 739677, tzinfo=utc)),
        ),
    ]
